# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdc27b0fc23c9d99e6c8b9152bc42a68457a411f63222298100c04c8a5f40a60e3542a1bd153cc26b6c1a8f128bac13739a2cee13026fc3a50480c430f26925a

test:
  secret_key_base: 456129a9d45eb66f93231cbe2ceabd1f2d0c2fe1f79714bfaab77490ced333a38bc968906738ecb515265d15a3a038428ebca114c4d423e7f1c2a194b8c83309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
